### ISSUE TITLE
Raise new named exceptions for some expected errors

### ISSUE THREAD

**Issue by luarx** [gnosis/gnosis-py#23]
Expected error messages:

- GETH
`ValueError{'code': -32000, 'message': 'transaction underpriced'}`
- OpenEthereum
`ValueError{'code': -32010, 'message': 'There are too many transactions in the queue. Your transaction was dropped due to limit. Try increasing the fee.'}`

Those error messages are expected when a tx is pending to be mined and a new tx is sent with the same parameters **but lower gasPrice**.

NOTE:
- Probably they should be added here:
https://github.com/gnosis/gnosis-py/blob/master/gnosis/eth/ethereum_client.py#L112
- `ReplacementTransactionUnderpriced `can be reused for this case if it fits

Thanks a bunch!

**Comment by Uxio0** [comment]
I think this is a different error than `ReplacementTransactionUnderpriced`. `ReplacementTransactionUnderpriced ` covers the case for sending a transaction with the same `nonce` than one transaction that's on the queue.

In this case the error can be raised even if there's no transaction on the queue for that address. That's why I will create a new exception, `TransactionUnderpriced `, do you think this is ok @luarx ?

**Comment by luarx** [comment]
Perfect, sounds good to me!
