### ISSUE TITLE
Gnosis-py doesn't work with eth brownie 1.15

### ISSUE THREAD

**Issue by Tritium-VLK** [gnosis/gnosis-py#48]
**Describe the bug**
Trying to use gnosis with brownie 1.15.  It's not working.  
**To Reproduce**
Due to a version incompatability between required web3 module versions.  This is resolved by https://github.com/gnosis/gnosis-py/pull/43, which has been pending for 14 days.

**Expected behavior**
It should be possible to use gnosis-py with brownie 1.15
**Additional context**

**Comment by Uxio0** [comment]
Hi @Tritium-VLK and thanks for your interest in our library. As you have seen on #43 tests are not passing due to a bug introduced in web3.py last versions and fixed in https://github.com/ethereum/web3.py/commit/1417eb878fff8d0dc379705b20af18feeb032462 . As soon as they release a new version we will do the same

**Comment by jeremyHD** [comment]
Hey gnosis team, is there a chance that #54 will be merge soon :) ?

**Comment by Uxio0** [comment]
It's done, a new version (v3.2.0) has been released. Thanks for your patience!
